# Generated by Django 4.2.30 on 2026-06-14 13:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a 3-letter ISO code.', regex='^[A-Z]{3}$')])),
                ('date', models.DateField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage')], max_length=16)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a 3-letter ISO code.', regex='^[A-Z]{3}$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('needs_review', 'Needs Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('raw_csv_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='api.group')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('anomaly', 'Anomaly'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(choices=[('duplicate_expense', 'Duplicate expense'), ('negative_amount', 'Negative amount'), ('missing_payer', 'Missing payer'), ('invalid_date', 'Invalid date'), ('settlement_logged_as_expense', 'Settlement logged as expense'), ('currency_mismatch', 'Currency mismatch'), ('unknown_member', 'Unknown member'), ('inactive_member', 'Inactive member'), ('amount_mismatch', 'Amount mismatch'), ('invalid_split', 'Invalid split'), ('duplicate_transaction', 'Duplicate transaction'), ('missing_category', 'Missing category')], max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('requires_approval', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.importbatch')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='api.importrow')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expense_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a 3-letter ISO code.', regex='^[A-Z]{3}$')])),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.group')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='settlement_receipts', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='settlement_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'date'], name='api_settlem_group_i_930341_idx'), models.Index(fields=['payer', 'payee'], name='api_settlem_payer_i_fe71a0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(check=models.Q(('payer', models.F('payee')), _negated=True), name='settlement_payer_not_payee'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['import_batch', 'status'], name='api_importr_import__4f2c88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importrow',
            unique_together={('import_batch', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['import_batch', 'rule_code'], name='api_importi_import__35d8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['import_batch', 'severity'], name='api_importi_import__bb8985_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status'], name='api_importb_status_ecf8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['imported_by'], name='api_importb_importe_dfb1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'user'], name='api_groupme_group_i_8c1132_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group'], name='api_groupme_group_i_bb6194_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.CheckConstraint(check=models.Q(('leave_date__gte', models.F('join_date')), ('leave_date__isnull', True), _connector='OR'), name='groupmember_leave_after_join'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user', 'join_date'), name='unique_group_user_join_date'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by'], name='api_group_created_db87df_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseparticipant',
            index=models.Index(fields=['user'], name='api_expense_user_id_935cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseparticipant',
            index=models.Index(fields=['expense'], name='api_expense_expense_ecbf39_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseparticipant',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='unique_participant_per_expense'),
        ),
        migrations.AddConstraint(
            model_name='expenseparticipant',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='participant_non_negative_amount'),
        ),
        migrations.AddConstraint(
            model_name='expenseparticipant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('percentage__gte', 0), ('percentage__lte', 100)), ('percentage__isnull', True), _connector='OR'), name='participant_percentage_range'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'date'], name='api_expense_group_i_a021a6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payer'], name='api_expense_payer_i_7fa26f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_reference'], name='api_expense_source__d450ef_idx'),
        ),
    ]
